export const PROFILE_LIST_REQUEST='PROFILE_LIST_REQUEST';
export const PROFILE_LIST_SUCCESS='PROFILE_LIST_SUCCESS';
export const PROFILE_LIST_FAIL='PROFILE_LIST_FAIL';

export const PROFILE_DETAIL_REQUEST='PROFILE_DETAIL_REQUEST';
export const PROFILE_DETAIL_SUCCESS='PROFILE_DETAIL_SUCCESS';
export const PROFILE_DETAIL_FAIL='PROFILE_DETAIL_FAIL';